# Generated by Django 4.1.1 on 2022-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, default='empty.png', upload_to='site')),
                ('socials_inst', models.URLField(blank=True, null=True)),
                ('socials_twitter', models.URLField(blank=True, null=True)),
                ('socials_facebook', models.URLField(blank=True)),
            ],
        ),
    ]
