# Generated by Django 4.1.1 on 2022-09-29 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
